name: Push updates to our social media accounts

on:
  push:
    branches:
      - master
      - fastring

jobs:
  push:
    runs-on: ubuntu-18.04

    steps:
      - name: Get the SHA of the commit before the push
        uses: actions/github-script@v3
        id: before-sha
        with:
          script: |
            const commit = await github.repos.getCommit({context.repo.owner, context.repo.repo, context.ref})
            return commit.parents[0].sha
          result-encoding: string

      - name: Pull Python code
        uses: actions/checkout@v2
        with:
          ref: source

      - name: Install dependencies
        run: |
          sudo apt-get install ffmpeg -y
          pip3 install requests
          pip3 install datetime
          pip3 install youtube-dl
          pip3 install pytz

      - name: Do the actual push
        env:
          GITHUB_BEFORE: ${{ steps.before-sha.outputs.result }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_PROD_CHAT_ID: ${{ secrets.TG_PROD_CHAT_ID }}
          TG_DBG_CHAT_ID: ${{ secrets.TG_DBG_CHAT_ID }}
        run: python3 push-telegram.py
