name: Push updates to our social media accounts

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [telegram, twitter]
    
    steps:
      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg -y
